name: ClashX

on:
  push:
    tags: [ v* ]
  workflow_dispatch:
    inputs:
      logLevel:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: test
      run: git rev-list --count origin/master..origin/meta
    
    - name: download meta core
      uses: robinraju/release-downloader@v1.8
      with:
        repository: 'MetaCubeX/Clash.Meta'
        tag: "v1.14.4"
        fileName: ".*darwin.*64-v.*.gz"

        # releaseId: "62870807"
        # fileName: ".*darwin.*64-alpha.*.gz"
        
        out-file-path: "clash.meta"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install deps
      run: bash install_dependency.sh

    - name: build infos
      run: python3 ClashX/add_build_info.py

    - name: build
      run: xcodebuild archive -workspace ClashX.xcworkspace -scheme ClashX -archivePath archive/ClashX.xcarchive -showBuildTimingSummary -allowProvisioningUpdates

    - name: build-SwiftUI
      run: |
        xcodebuild -resolvePackageDependencies -project ClashX\ SwiftUI.xcodeproj
        xcodebuild archive -project ClashX\ SwiftUI.xcodeproj -scheme ClashX\ Meta -archivePath archive/ClashX\ SwiftUI.xcarchive -showBuildTimingSummary -allowProvisioningUpdates


    - name: create zip
      run: |
        ditto -c -k --sequesterRsrc --keepParent archive/ClashX.xcarchive/Products/Applications/ClashX\ Meta.app ClashX\ Meta.zip
        ditto -c -k --sequesterRsrc --keepParent archive/ClashX\ SwiftUI.xcarchive/Products/Applications/ClashX\ Meta.app ClashX\ Meta\ SwiftUI\ macOS\ 12.0+.zip

    - name: upload Artifact
      uses: actions/upload-artifact@v3
      if: "!startsWith(github.ref, 'refs/tags/')"
      with:
        name: "ClashX Meta.zip"
        path: "*.zip"

    - name: upload build to github
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        generate_release_notes: true
        files: |
          "ClashX Meta.zip"
          "ClashX Meta SwiftUI macOS 12.0+.zip"

